name: user_repository
description: The repo that handles users
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  firebase_auth:
  cloud_firestore:
  rxdart:





dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
